variable "bastion_host_enabled" {}
variable "cluster_name" {}
variable "cni_enable" {}
variable "control_plane_instance_type" {}
variable "control_plane_instance_replicas" {}
variable "ingress_instance_type" {}
variable "ingress_replicas" {}
variable "kubernetes_version" {}
variable "pod_cidr_block" {}
variable "ssh_key_name" {}
variable "worker_instance_type" {}
variable "worker_replicas" {}
variable "vpc_cidr_block" {}
variable "aws_access_key_id" {}
variable "aws_region" {}
variable "aws_secrets_access_key" {}
variable "bootstrap_iam" {}
variable "clusterawsadm_distro" {}
variable "clusterawsadm_version" {}
variable "exp_eks_add_roles" {}
variable "exp_eks_iam" {}
variable "exp_eks" {}
variable "exp_machine_pool" {}
variable "kubeconfig_context" {}
